name: Update Notice Year

on:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Current year
        run: "echo CURRENT=$(date +%Y) >> $GITHUB_ENV"

      - name: Set Previous Year
        run: "echo PREVIOUS=$(($CURRENT-1)) >> $GITHUB_ENV"

      - name: Update NOTICE
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ env.PREVIOUS }}
          replace: ${{ env.CURRENT }}
          include: "NOTICE"
          regex: false

      - name: Commit files
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Updated Notice Year" -a

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update Notice Year
          branch: update-notice
